services:
  tesnix:
    image: tesnix-final
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/.Xauthority:ro