FROM ubuntu:noble

RUN apt-get update && apt-get install -y \
 qemu-system-x86 \
 grub-pc-bin \
 make \
 xorriso \
 libisl23 \
 libmpc3 \
 libsdl2-2.0-0 \
 libgtk-3-0 \
 && rm -rf /var/lib/apt/lists/*