FROM debian:trixie-slim

RUN apt-get update && apt-get install -y \
 build-essential \
 bison \
 flex \
 libgmp3-dev \
 libmpfr-dev \
 libmpc-dev \
 libncurses-dev \
 libexpat1-dev \
 zlib1g-dev \
 && rm -rf /var/lib/apt/lists/*